<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../../public/css/clientes.css">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600&family=Quicksand:wght@700&family=Roboto&display=swap" rel="stylesheet">
    <title>Usuários cadastrados</title>
  </head>
  <body>
    <div class="container">
      <div class="clientsCard">
        <div class="clientsCardHeader">
          <h1 class="clientsCardID">ID do Usuário: <?php echo $idUser ?></h1>
          <h1 class="clientsCardTitle">Lista de usuários</h1>
          <a class="clientsCardLogout" href="/login/logout">Sair da Conta</a>
        </div>        
        <div class="clientsInfoContent">
          <?php 
            if ($clients != null && !empty($clients)){
              foreach ($clients as $client) {
                echo '<div class="clientInfo">';
                echo '<div class="infos">';
                echo '<p class="clientID">Código do usuário: ' . $client['id_client'] . '</p>';
                echo '<p>Nome: ' . $client['client_name'] . '</p>';
                echo '<p>E-mail: ' . $client['email'] . '</p>';
                echo '<p>Senha: ' . $client['password'] . '</p>';
                echo '<p>Contato: ' . $client['tell'] . '</p>';
                echo '<p>Idade: ';
                echo $client['age'] <= 18 ? $client['age'] . ' (Menor de idade)</p>' : $client['age'] . ' (Maior de idade)</p>';
                echo '</div>';
                echo '<div class="buttons">';
                echo '<a class="buttonEdit" href="clientes/edit/' . $client['id_client'] . '">Editar</a>';
                echo '<a class="buttonDelete" href="clientes/delete/' . $client['id_client'] . '">Excluir</a>';
                echo '</div>';
                echo '</div>';
              }
            } else {
              echo '<div class="noClientsMessage">';
              echo '<h1 class="noClientsMessageText">Nenhum cliente cadastrado!</h1>';
              echo '</div>';
            }
          ?>
        </div>
      </div> 
    </div>
  </body>
</html>