<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../../public/css/index.css">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600&family=Quicksand:wght@700&family=Roboto&display=swap" rel="stylesheet">
    <title><?php echo $pageTitle; ?></title>
  </head>
  <body>
    <h1 class="registerTitle"><?php echo $title; ?></h1>
    <p class="clientInfo"><?php echo 'boa tarde!'//var_dump($clients); ?>olá</p>
  </body>
</html>