<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../../public/css/confirmacao.css">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600&family=Quicksand:wght@700&family=Roboto&display=swap" rel="stylesheet">
    <title>Confirmar Cadastro</title>
  </head>
  <body>
    <div class="container">
      <?php 
        echo $response ? '<h1 class="confirmRegisterTitle">Seu cliente foi cadastrado!</h1>' : '<h1 class="registerTitle">Falha ao cadastrar cliente!</h1>'
      ?>   
    </div>       
  </body>
</html>