<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../../public/css/index.css">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600&family=Quicksand:wght@700&family=Roboto&display=swap" rel="stylesheet">
    <title><?php echo !isset($clientInfo) ? 'Cadastro de Usuário' : 'Atualizar Usuário'?></title>
  </head>
  <body >
    <div class="container">
      <div class="registerCard">
        <h1 class="registerTitle">Cadastro de Usuário</h1>
        
        <form id="registerUserForm" 
          action="<?php
            echo !isset($clientInfo) ? 
            '/clientes/register_user' : 
            '/clientes/edit/' . $clientInfo['id_client'] 
          ?>"
          method="POST"
        >
          <div class="inputStyle">
            <label for="nameInput">Nome:</label>
            <input 
              type="text" 
              id="nameInput" 
              name="name" 
              placeholder="Insira seu nome" 
              value="<?php
                echo !isset($clientInfo) ?
                null :
                $clientInfo['client_name']
              ?>"
              maxlength="40" 
              required
            >
          </div>

          <div class="inputStyle">
            <label id="emailLabel" for="emailInput">E-mail:</label>
            <input 
              type="text" 
              id="emailInput" 
              name="email" 
              placeholder="Insira seu e-mail" 
              value="<?php 
                echo !isset($clientInfo) ?
                null :
                $clientInfo['email']
              ?>"
              maxlength="33" 
              required
            >
          </div>

          <div class="inputStyle">
            <label id="passwordLabel" for="passwordInput">Senha:</label>
            <input 
              type="text" 
              id="passwordInput" 
              name="password" 
              placeholder="<?php 
                echo !isset($clientInfo) ?
                'Insira sua senha' :
                'Insira sua nova senha'
              ?>"
              maxlength="20" 
              <?php 
                echo !isset($clientInfo) ?
                'required' :
                null
              ?>
            >
          </div>
          
          <div class="inputStyle">
            <label id="telLabel" for="tellInput">Telefone:</label>
            <input 
              Type="text" 
              id="tellInput" 
              name="tell" 
              placeholder="Insira sua telefone" 
              value="<?php
                echo !isset($clientInfo) ?
                null :
                $clientInfo['tell']
              ?>"
              maxlength="13" 
              required
            >
          </div>

          <div class="inputStyleFinal">
            <label id="ageLabel" for="ageInput">Idade:</label>
            <input 
              Type="text" 
              pattern="\d*" 
              id="ageInput" 
              name="age" 
              placeholder="Insira sua idade" 
              value="<?php 
                echo !isset($clientInfo) ?
                null :
                $clientInfo['age']
              ?>"
              required>
          </div>

          <div class="redirectLoginContainer">
            <a class="redirectLoginAnchor" href="/login">Fazer Login ></a>
          </div>
        </form>
        
        <div class="buttonGroup">
          <?php 
            echo !isset($clientInfo) ?
            '<button type="reset" form="registerUserForm">Cancelar</button>' :
            '<a class="backAnchor" href="/clientes">Voltar</a>'
          ?>
          <button type="submit" form="registerUserForm">Enviar</button>
        </div>        
      </div>  
    </div>
  </body>
</html>